apiVersion: apps/v1
kind: Deployment
metadata:
  name: watermark-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watermark
  template:
    metadata:
      labels:
        app: watermark
    spec:
      containers:
      - name: watermark-app
        image: us-central1-docker.pkg.dev/thinking-banner-421414/watermark-repo/watermark-gke:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"