apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: process-deployment
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: process
  template:
    metadata:
      labels:
        app: process
    spec:
      serviceAccountName: watermark-sa
      containers:
        - name: process
          image: us-central1-docker.pkg.dev/thinking-banner-421414/watermark-repo/process:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
